### ISSUE TITLE
単一勝者ルール戦略について

### ISSUE THREAD

**Issue by KoyoKawano** [hiro-tacky/MoFGBML_roma#3]
識別率計算が僕のpython上での実装と異なることを確認してしまった．
違いは，
cilabo.fuzzy.classifier.classification.impl.SingleWinnerRuleSelection
での全てのルールに対して適合度とルール重みの積が0になったパターンの処理．

現在は，変数max 初期化にDouble.MIN_VALUEが使用されるが，Double.MIN_VALUE > 0 であるため，以降更新が起きず，
最終的にルールリストの0番目のルールを返すようになってる．

cilabo.fuzzy.classifier.classification.impl.SingleWinnerRuleSelection　23行目のmaxの初期値を0未満にすることで，僕のpython上の実装と識別率計算が一致することを確認した．

修正求む．．．．

**Comment by hiro-tacky** [comment]
Double.MIN_VALUE って正の値なんか．．．
 -(ﾏｲﾅｽ) Double.MAX_VALUE に変更します
